stages:
  - build
  - test

variables:
  PYTHON_VERSION: "3.12"

build:
  stage: build
  image: python:${PYTHON_VERSION}
  script:
    - python --version
    - pip install --upgrade pip
    - pip install pytest
    - pip install pytest-html
  artifacts:
    paths:
      - .venv/
    expire_in: 1 hour
  cache:
    key: "pip-cache"
    paths:
      - "~/.cache/pip/"

unit-tests:
  stage: test
  image: python:${PYTHON_VERSION}
  script:
    - python --version
    - pip install --upgrade pip
    - pip install pytest
    - pip install pytest-html
    - pytest tests/ --junitxml=tests/junit.xml --html=tests/pytest_report.html
  dependencies:
    - build
  artifacts:
    when: always
    paths:
      - tests/junit.xml
      - tests/pytest_report.html
    reports:
      junit: tests/junit.xml