image: python:3.11

stages:
  - build
  - test

before_script:
  - python --version
  - pip install --upgrade pip
  - pip install poetry
  - poetry remove torch
  - poetry install
  - export PYTHONPATH=$CI_PROJECT_DIR
  - source `poetry env info --path`/bin/activate

build:
  stage: build
  script:
    - python --version
    - pip install pytest pytest-html 
    - pip install torch
  artifacts:
    paths:
      - .venv/
    expire_in: 1 hour
  cache:
    key: "pip-cache"
    paths:
      - "~/.cache/pip/"

unit-tests:
  stage: test
  dependencies:
    - build
  script:
    - pip install pillow
    - pytest tests/ --junitxml=tests/junit.xml --html=tests/pytest_report.html
  artifacts:
    when: always
    paths:
      - tests/junit.xml
      - tests/pytest_report.html
    reports:
      junit: tests/junit.xml

code_coverage:
  stage: test
  needs: 
    - unit-tests
  script:
    - pip install pillow
    - pytest --cov=api --cov=app --cov=controller --cov=processing --cov=scheduling --cov=parking_spot_status.py --cov-report=term
  coverage: '/TOTAL.*\s+(\d+\%)$/'
